if(typeof sIFR == "function") {
  sIFR.replaceElement("html#en body.front #content-area h2", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#000000", sLinkColor: "#000000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en #content-area h2", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#003359", sLinkColor: "#000000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en #sidebar-right .content h2", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#003359", sLinkColor: "#000000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en h1.title", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#000000", sLinkColor: "#000000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en #hm-content h3", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#ff0000", sLinkColor: "#ff0000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en #cbox strong", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#FFFFFF", sLinkColor: "#FFFFFF", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en primary ul.links li a", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#FFFFFF", sLinkColor: "#FFFFFF", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en #sidebar-right h2.title", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20roman%20bold.swf", sColor: "#FE0000", sLinkColor: "#FE0000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en body.page-home2 #sidebar-right .content h2", named({sFlashSrc: "/sites/arc/files/render/akzidenz%20grotesk%20ce%20light%20bold.swf", sColor: "#666666", sLinkColor: "#000000", sBgColor: "#FFFFFF", sWmode: "transparent", sFlashVars: "textalign=left"}));
  sIFR.replaceElement("html#en body.page-dmd-products-anti-kpb h1.title", named({sFlashSrc: "/", sColor: "#000000", sLinkColor: "#000000", sBgColor: "#FFFFFF", sFlashVars: "textalign=left"}));
};
